<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EPINHYDW0D30" failures="0" tests="38" name="calculator.TestCalculator" time="1.933" errors="1" timestamp="2022-03-05T21:01:06 IST" skipped="1">
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.032"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.070"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.044"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.036"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.095"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.032"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.067"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.031"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.047"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.067"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.048"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.023"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.025"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.026"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.005">
    <error message="Step [Library has following book] is defined with 1 parameters at &#039;calculator.StepDefinitionCalculator.library_has_following_book(io.cucumber.datatable.DataTable)&#039;.
However, the gherkin step has 0 arguments.
Step text: Library has following book" type="io.cucumber.core.exception.CucumberException">
      <![CDATA[io.cucumber.core.exception.CucumberException: Step [Library has following book] is defined with 1 parameters at 'calculator.StepDefinitionCalculator.library_has_following_book(io.cucumber.datatable.DataTable)'.
However, the gherkin step has 0 arguments.
Step text: Library has following book
at io.cucumber.core.runner.PickleStepDefinitionMatch.arityMismatch(PickleStepDefinitionMatch.java:83)
at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:42)
at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:86)
at io.cucumber.core.runner.TestStep.run(TestStep.java:57)
at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
at io.cucumber.core.runner.TestCase.run(TestCase.java:95)
at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)
at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$3(CucumberExecutionContext.java:151)
at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:151)
at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.115"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.034"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.030"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.055"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.034"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.123"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.063"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.087"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.114"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.161"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.008"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.060"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.032"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.036"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.047"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.039"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.043"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.030"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.024"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.049"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.032"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="runScenario" time="0.069"/>
  <system-out/>
  <testcase classname="calculator.TestCalculator" name="met">
    <skipped/>
  </testcase> <!-- met -->
  <system-out/>
</testsuite> <!-- calculator.TestCalculator -->
